working district unit tests

diff --git a/build b/build
--- a/build
+++ b/build
@@ -27,38 +27,83 @@ start_container () {
             docker-compose -d up
             COMPOSE_EXIT_CODE=$?
             ;;
+
         reg)
             echo "Spinning up the reg env for ${APPNAME} program"
             docker-compose -d -f docker-compose-regression.yml up
             COMPOSE_EXIT_CODE=$?
             ;;
+
         dev)
             echo "Spinning up a dev env for ${APPNAME} program"
             docker-compose -f docker-compose-development.yml run --rm $2
             COMPOSE_EXIT_CODE=$?
             ;;
+
         test)
             echo "Spinning up the test env ${APPNAME} program"
             echo $2
             if [ -z $2 ];then
-                echo run all
-                docker-compose -f docker-compose-test.yml up
-            else
-                docker-compose -f docker-compose-test.yml up --rm $2
+                echo run all tests
                 # docker-compose -f docker-compose-test.yml up
+                docker-compose -f docker-compose-test.yml run --rm lint
+                LINT_TEMP_ERROR_CODE=$?
+
+                docker-compose -f docker-compose-test.yml run --rm unit
+                UNIT_TEMP_ERROR_CODE=$?
+
+                docker-compose -f docker-compose-test.yml run --rm functional
+                FUNCTIONAL_TEMP_ERROR_CODE=$?
+
+                docker-compose -f docker-compose-test.yml run --rm coverage
+                COVERAGE_TEMP_ERROR_CODE=$?
+                
+                COMPOSE_EXIT_CODE=0
+                if [ $LINT_TEMP_ERROR_CODE -ne 0 ]; then
+                    echo 'lint tests failed'
+                    COMPOSE_EXIT_CODE=1; fi
+
+                if [ $UNIT_TEMP_ERROR_CODE -ne 0 ]; then
+                    echo 'unit tests failed'
+                    COMPOSE_EXIT_CODE=1; fi
+
+                if [ $FUNCTIONAL_TEMP_ERROR_CODE -ne 0 ]; then
+                    echo 'functional tests failed'
+                    COMPOSE_EXIT_CODE=1; fi
+
+                if [ $COVERAGE_TEMP_ERROR_CODE -ne 0 ]; then
+                    echo 'coverage tests failed'
+                    COMPOSE_EXIT_CODE=1; fi
+
+                if [ $COMPOSE_EXIT_CODE -ne 0 ]; then
+                    echo 'At least one test failed. sad day'
+                else
+                    echo 'All tests succeeded!'
+                fi
+
+
+            else
+                docker-compose -f docker-compose-test.yml run --rm $2
+                COMPOSE_EXIT_CODE=$?
             fi
+            ;;
+
+        coverage)
+            echo "Generating coverage report"
+            docker-compose -f docker-compose-test.yml run --rm coverage
             COMPOSE_EXIT_CODE=$?
-            
             ;;
     esac
 }
 
 clean () {
     echo clean
+    docker rm $(docker stop $(docker ps -a --filter="name=civ_vi_city_planner" --format="{{.ID}}"))
 }
 
 stop () {
     echo stop
+    docker stop $(docker ps -a --filter="name=civ_vi_city_planner" --format="{{.ID}}")
 }
 
 clense () {
@@ -111,6 +156,10 @@ case "$1" in
 
     test)
         start_container "test" "${2}"
+        ;;
+
+    coverage)
+        start_container "coverage" "${2}"
         ;;
 
 
